
const Data=[
        {"key":1,
        "url":"https://bit.ly/3PKMFt9","Name":"A","Rent":20000,"location":"lucknow","time":"jan","type":"housing"
        },
        {"key":2,
          "url":"https://bit.ly/3PKMFt9","Name":"B","Rent":20000,"location":"delhi","time":"feb","type":"housing"
        },
        {"key":3,
          "url":"https://bit.ly/3PKMFt9","Name":"C","Rent":20000,"location":"Jaipur","time":"march","type":"Commercial"
        },
        {"key":4,
          "url":"https://bit.ly/3PKMFt9","Name":"D","Rent":10000,"location":"lucknow","time":"april","type":"housing"
        },
        {"key":45,
          "url":"https://bit.ly/3PKMFt9","Name":"E","Rent":10000,"location":"delhi","time":"may","type":"housing"
        },
        {"key":46,
          "url":"https://bit.ly/3PKMFt9","Name":"F","Rent":10000,"location":"Lucknow","time":"june","type":"housing"
        },
        {"key":471,
          "url":"https://bit.ly/3PKMFt9","Name":"G","Rent":10000,"location":"lucknow","time":"july","type":"Commercial"
        },
        {"key":472,
          "url":"https://bit.ly/3PKMFt9","Name":"H","Rent":10000,"location":"delhi","time":"aug","type":"Commercial"
        },
        {"key":473,
          "url":"https://bit.ly/3PKMFt9","Name":"I","Rent":10000,"location":"Jaipur","time":"sep","type":"Rental"
        },
        {"key":474,
          "url":"https://bit.ly/3PKMFt9","Name":"J","Rent":10000,"location":"lucknow","time":"oct","type":"Rental"
        },
        {"key":475,
          "url":"https://bit.ly/3PKMFt9","Name":"K","Rent":20000,"location":"delhi","time":"Nov","type":"Rental"
        },
        {"key":476,
          "url":"https://bit.ly/3PKMFt9","Name":"L","Rent":20000,"location":"Jaipur","time":"Dec","type":"Rental"
        },
         {"key":4476,
        "url":"https://bit.ly/3PKMFt9","Name":"A","Rent":20000,"location":"lucknow","time":"jan","type":"housing"
        },
        {"key":4736,
          "url":"https://bit.ly/3PKMFt9","Name":"B","Rent":3000,"location":"delhi","time":"feb","type":"housing"
        },
        {"key":4176,
          "url":"https://bit.ly/3PKMFt9","Name":"C","Rent":3000,"location":"Jaipur","time":"march","type":"Commercial"
        },
        {"key":47336,
          "url":"https://bit.ly/3PKMFt9","Name":"D","Rent":3000,"location":"lucknow","time":"april","type":"housing"
        },
        {"key":47356,
          "url":"https://bit.ly/3PKMFt9","Name":"E","Rent":3000,"location":"delhi","time":"may","type":"housing"
        },
        {"key":473556,
          "url":"https://bit.ly/3PKMFt9","Name":"F","Rent":3000,"location":"Jaipur","time":"june","type":"housing"
        },
        {"key":47736,
          "url":"https://bit.ly/3PKMFt9","Name":"G","Rent":9000,"location":"lucknow","time":"july","type":"Commercial"
        },
        {"key":473366,
          "url":"https://bit.ly/3PKMFt9","Name":"H","Rent":9000,"location":"delhi","time":"aug","type":"Commercial"
        },
        {"key":47331166,
          "url":"https://bit.ly/3PKMFt9","Name":"I","Rent":9000,"location":"Jaipur","time":"sep","type":"Rental"
        },
        {"key":4733662,
          "url":"https://bit.ly/3PKMFt9","Name":"J","Rent":9000,"location":"lucknow","time":"oct","type":"Rental"
        },
        {"key":4733663,
          "url":"https://bit.ly/3PKMFt9","Name":"K","Rent":9000,"location":"delhi","time":"Nov","type":"Rental"
        },
        {"key":4733664,
          "url":"https://bit.ly/3PKMFt9","Name":"L","Rent":9000,"location":"Jaipur","time":"Dec","type":"Rental"
        }
        
        ]
export default Data


